# NDS-Signer: MicroPython user C module wrapping libsecp256k1.
# Wrapper from diybitcoinhardware/secp256k1-embedded (MIT); the library itself
# is the pinned submodule third_party/secp256k1 (bitcoin-core, MIT).
SECP256K1_MOD_DIR := $(USERMOD_DIR)
SECP256K1_LIB_DIR := $(USERMOD_DIR)/../../../third_party/secp256k1
# generated by mpy/Makefile (libsecp256k1's own gen_context tool)
SECP256K1_GEN_DIR := $(USERMOD_DIR)/../../../build/secp256k1_gen

# Only the wrapper defines Python objects (and qstrs).
SRC_USERMOD += $(SECP256K1_MOD_DIR)/libsecp256k1.c
# Library sources: compiled by ports that use this file directly (unix port);
# the DSi build compiles them in mpy/Makefile.
SRC_USERMOD_LIB_C += $(SECP256K1_LIB_DIR)/src/secp256k1.c \
                     $(SECP256K1_MOD_DIR)/config/ext_callbacks.c

CFLAGS_USERMOD += -I$(SECP256K1_LIB_DIR) -I$(SECP256K1_LIB_DIR)/src \
                  -I$(SECP256K1_MOD_DIR)/config -I$(SECP256K1_GEN_DIR) -DHAVE_CONFIG_H \
                  -Wno-unused-function -Wno-pointer-sign
