#!/usr/bin/env python3
"""Convert a BDF bitmap font (<= 8x8 glyphs) into a libnds console font:
256 glyphs x 8 bytes, 1 bpp, glyph index = character code (ISO-8859-1).
Glyphs are centred horizontally in the 8x8 cell.

    tools/bdf_to_ndsfont.py lib/fonts/spleen-5x8.bdf build/generated/nds_font.c
"""
import sys


def parse_bdf(path):
    glyphs, cur, bitmap = {}, None, None
    for line in open(path, encoding="latin-1"):
        parts = line.split()
        if not parts:
            continue
        if parts[0] == "ENCODING":
            cur = {"code": int(parts[1])}
        elif parts[0] == "BBX" and cur is not None:
            cur["bbx"] = tuple(int(v) for v in parts[1:5])
        elif parts[0] == "BITMAP":
            bitmap = []
        elif parts[0] == "ENDCHAR":
            cur["rows"] = bitmap
            glyphs[cur["code"]] = cur
            cur, bitmap = None, None
        elif bitmap is not None:
            bitmap.append(int(parts[0], 16))
    return glyphs


# Box-drawing glyphs on free control codes (0x1B is ESC, skipped): unlike the
# 5-pixel-wide letters they fill the whole 8x8 cell, so lines connect.
# Must match seedsigner/gui/nds_ui.py (BOX_* constants).
def _box_glyph(h_rows, v_cols, h_span, v_span):
    rows = [0] * 8
    for y in h_rows:
        for x in range(h_span[0], h_span[1] + 1):
            rows[y] |= 1 << x
    for x in v_cols:
        for y in range(v_span[0], v_span[1] + 1):
            rows[y] |= 1 << x
    return rows


BOX_GLYPHS = {
    # single line: horizontal row 3, vertical column 3
    0x10: _box_glyph([3], [], (0, 7), None),            # ─
    0x11: _box_glyph([], [3], None, (0, 7)),            # │
    0x12: _box_glyph([3], [3], (3, 7), (3, 7)),         # ┌
    0x13: _box_glyph([3], [3], (0, 3), (3, 7)),         # ┐
    0x14: _box_glyph([3], [3], (3, 7), (0, 3)),         # └
    0x15: _box_glyph([3], [3], (0, 3), (0, 3)),         # ┘
    # double line (highlight): rows 2/4, columns 2/4
    0x16: _box_glyph([2, 4], [], (0, 7), None),         # ═
    0x17: _box_glyph([], [2, 4], None, (0, 7)),         # ║
}


def _double_corner(right, down):
    rows = [0] * 8
    xs = range(2, 8) if right else range(0, 5)
    ys = range(2, 8) if down else range(0, 5)
    outer_row, inner_row = (2, 4) if down else (4, 2)
    outer_col, inner_col = (2, 4) if right else (4, 2)
    for x in xs:
        rows[outer_row] |= 1 << x
    for x in (range(inner_col, 8) if right else range(0, inner_col + 1)):
        rows[inner_row] |= 1 << x
    for y in ys:
        rows[y] |= 1 << outer_col
    for y in (range(inner_row, 8) if down else range(0, inner_row + 1)):
        rows[y] |= 1 << inner_col
    return rows


BOX_GLYPHS.update({
    0x18: _double_corner(True, True),    # ╔
    0x19: _double_corner(False, True),   # ╗
    0x1A: _double_corner(True, False),   # ╚
    0x1C: _double_corner(False, False),  # ╝
})


def main():
    src, out = sys.argv[1], sys.argv[2]
    glyphs = parse_bdf(src)
    data = bytearray(256 * 8)
    for code in range(256):
        g = glyphs.get(code)
        if g is None:
            continue
        w, h, xoff, yoff = g["bbx"]
        nbytes = (w + 7) // 8
        left = (8 - w) // 2
        top = 8 - h - (yoff + 1) if h < 8 else 0  # font baseline: descent 1
        for r, bits in enumerate(g["rows"]):
            y = top + r
            if not 0 <= y < 8:
                continue
            for x in range(w):
                if bits & (1 << (nbytes * 8 - 1 - x)):
                    # libnds 1bpp fonts: bit 0 is the leftmost pixel
                    data[code * 8 + y] |= 1 << (left + x)
    for code, rows in BOX_GLYPHS.items():
        data[code * 8:code * 8 + 8] = bytes(rows)
    with open(out, "w") as f:
        f.write("/* GENERATED by tools/bdf_to_ndsfont.py from %s - do not edit.\n"
                " * Spleen font: Copyright (c) 2018-2026, Frederic Cambus, BSD 2-Clause\n"
                " * (lib/fonts/LICENSE.spleen). */\n" % src.split("/")[-1])
        f.write("#include <stdint.h>\n\n")
        f.write("const uint8_t g_ndsFont[%d] __attribute__((aligned(4))) = {\n" % len(data))
        for i in range(0, len(data), 16):
            f.write("\t" + ", ".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
        f.write("};\n")


if __name__ == "__main__":
    main()
