#!/usr/bin/env python3
"""Write tests/vectors/*.txt as a Python module (DATA dict) so test scripts can
run on the DSi, which has no filesystem. SPIKE / test builds only."""
import pathlib
import sys

src, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
data = {p.name: p.read_text(encoding="utf-8") for p in sorted(list(src.glob("*.txt")) + list(src.glob("*.json")))}
out.write_text("# GENERATED by tools/freeze_vectors.py - public test data only\nDATA = %r\n" % data)
