#!/usr/bin/env python3
"""Generate seedsigner/gui/_upstream.py for NDS-Signer's native GUI.

NDS-Signer replaces SeedSigner's Pillow-based `seedsigner.gui` with native
screens, but the upstream views must keep working unmodified. This tool reads
the upstream GUI sources and emits:

  * the constant classes the views use (GUIConstants, FontAwesomeIconConstants,
    SeedSignerIconConstants), copied verbatim from gui/components.py;
  * SCREEN_FIELDS: for every upstream dataclass in gui/ (screens and
    ButtonOption), its fields in order (including inherited ones) with their
    default as a zero-argument callable, so native screens accept exactly the
    same keyword arguments and get the same default texts/buttons as upstream.

Defaults that reference anything outside the emitted namespace (fonts, PIL,
...) become None: they only affect Pillow rendering.

    tools/gen_gui_api.py third_party/seedsigner/src build/.../gui/_upstream.py
"""
import ast
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
import screen_api  # noqa: E402

CONSTANT_CLASSES = ("GUIConstants", "FontAwesomeIconConstants", "SeedSignerIconConstants")
KNOWN_NAMES = set(CONSTANT_CLASSES) | {
    "SettingsConstants", "Settings", "_mft", "_", "ButtonOption", "field",
    "True", "False", "None", "list", "dict", "tuple",
}

HEADER = '''# GENERATED by tools/gen_gui_api.py from upstream SeedSigner {commit}
# ({components}). Do not edit.
from gettext import gettext as _
from seedsigner.helpers.l10n import mark_for_translation as _mft
from seedsigner.models.settings import Settings
from seedsigner.models.settings_definition import SettingsConstants


def ButtonOption(*args, **kwargs):
    # resolved lazily: defaults are only evaluated when a screen is created
    from seedsigner.gui.screens.screen import ButtonOption as _ButtonOption
    return _ButtonOption(*args, **kwargs)


'''


def names_in(expr):
    return {n.id for n in ast.walk(expr) if isinstance(n, ast.Name)}


def default_callable(src):
    """Upstream default source -> source of a zero-arg callable."""
    if src is None:
        return "None"  # required field
    expr = ast.parse(src, mode="eval").body
    # field(default=...) / field(default_factory=...)
    if isinstance(expr, ast.Call) and isinstance(expr.func, ast.Name) and expr.func.id == "field":
        for kw in expr.keywords:
            if kw.arg == "default_factory":
                inner = kw.value
                if names_in(inner) - KNOWN_NAMES:
                    return "lambda: None"
                return "lambda: (%s)()" % ast.unparse(inner)
            if kw.arg == "default":
                expr = kw.value
                break
        else:
            return "lambda: None"
    if names_in(expr) - KNOWN_NAMES:
        return "lambda: None"
    return "lambda: %s" % ast.unparse(expr)


POST_INIT_ATTRS = {"title", "button_data", "show_back_button", "show_power_button",
                   "status_headline", "text", "is_bottom_list"}


def _safe(expr):
    """Only names we emit, and attribute access on self."""
    for n in ast.walk(expr):
        if isinstance(n, ast.Name) and n.id not in KNOWN_NAMES | {"self"}:
            return False
    return True


def _self_attr(target):
    if (isinstance(target, ast.Attribute) and isinstance(target.value, ast.Name)
            and target.value.id == "self" and target.attr in POST_INIT_ATTRS):
        return target.attr
    return None


def post_init_assigns(cls):
    out = []
    for fn in cls.body:
        if not (isinstance(fn, ast.FunctionDef) and fn.name == "__post_init__"):
            continue
        for stmt in fn.body:  # top level only: unconditional or `if not self.x:`
            if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1:
                attr = _self_attr(stmt.targets[0])
                if attr and _safe(stmt.value):
                    out.append((attr, False, ast.unparse(stmt.value)))
            elif (isinstance(stmt, ast.If) and not stmt.orelse and len(stmt.body) == 1
                  and isinstance(stmt.test, ast.UnaryOp) and isinstance(stmt.test.op, ast.Not)
                  and isinstance(stmt.body[0], ast.Assign)):
                attr = _self_attr(stmt.test.operand)
                inner = stmt.body[0]
                if attr and len(inner.targets) == 1 and _self_attr(inner.targets[0]) == attr \
                        and _safe(inner.value):
                    out.append((attr, True, ast.unparse(inner.value)))
    return out


def main():
    src_root, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    commit = sys.argv[3] if len(sys.argv) > 3 else "(unknown commit)"

    components = src_root / "seedsigner/gui/components.py"
    tree = ast.parse(components.read_text())
    parts = [HEADER.format(commit=commit, components="seedsigner/gui/components.py")]
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name in CONSTANT_CLASSES:
            parts.append(ast.unparse(node) + "\n\n\n")

    classes = screen_api.load(src_root)
    parts.append("SCREEN_FIELDS = {\n")
    for name in sorted(classes):
        fields = screen_api.all_fields(classes, name)
        if not fields:
            continue
        parts.append("    %r: (\n" % name)
        for fname, default in fields:
            parts.append("        (%r, %s),\n" % (fname, default_callable(default)))
        parts.append("    ),\n")
    parts.append("}\n\n")

    # simple attribute assignments from upstream __post_init__ methods
    # (titles, buttons...): `self.a = expr` and `if not self.a: self.a = expr`
    parts.append("POST_INIT = {\n")
    for path in sorted((src_root / "seedsigner/gui").rglob("*.py")):
        for node in ast.parse(path.read_text()).body:
            if not isinstance(node, ast.ClassDef):
                continue
            assigns = post_init_assigns(node)
            if assigns:
                parts.append("    %r: (\n" % node.name)
                for attr, only_if_falsy, expr in assigns:
                    parts.append("        (%r, %r, lambda self: %s),\n" % (attr, only_if_falsy, expr))
                parts.append("    ),\n")
    parts.append("}\n\n")

    # plain class-level constants (e.g. SeedAddPassphraseScreen.
    # KEYBOARD__LOWERCASE_BUTTON_TEXT), which upstream views read
    parts.append("CLASS_ATTRS = {\n")
    for path in sorted((src_root / "seedsigner/gui").rglob("*.py")):
        for node in ast.parse(path.read_text()).body:
            if not isinstance(node, ast.ClassDef) or node.name in CONSTANT_CLASSES:
                continue
            attrs = []
            for stmt in node.body:
                if (isinstance(stmt, ast.Assign) and len(stmt.targets) == 1
                        and isinstance(stmt.targets[0], ast.Name)
                        and not (names_in(stmt.value) - (KNOWN_NAMES - {"ButtonOption", "field"}))):
                    attrs.append((stmt.targets[0].id, ast.unparse(stmt.value)))
            if attrs:
                parts.append("    %r: {\n" % node.name)
                for attr, value in attrs:
                    parts.append("        %r: %s,\n" % (attr, value))
                parts.append("    },\n")
    parts.append("}\n\n")

    # module and bases of every upstream GUI class, so native modules can
    # provide generic stand-ins for screens they do not implement yet
    parts.append("SCREEN_INFO = {\n")
    for name in sorted(classes):
        info = classes[name]
        module = pathlib.Path(info["module"]).stem
        bases = tuple(b.split(".")[-1] for b in info["bases"])
        parts.append("    %r: (%r, %r),\n" % (name, module, bases))
    parts.append("}\n")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(parts))


if __name__ == "__main__":
    main()
