#!/usr/bin/env python3
"""Turns SeedSigner's translations (seedsigner-translations/l10n/<locale>/
LC_MESSAGES/messages.po) into Python modules frozen into the ROM:

    nds_l10n_<locale>.py   MESSAGES = {msgid: msgstr}, PLURALS = {msgid: [forms]}
    nds_l10n_index.py      LOCALES = [...] (the locales included)
    l10n_manifest.py       freezes them (included by mpy/manifest.py)

NDS-Signer's own strings (l10n/<locale>.po in this repository) are merged
into SeedSigner's translation of the same locale.

A locale is included only if every character of its translations is in the
UI fonts (tools/ttf_to_ndsfont.py TEXT_CHARS), so no text renders as "?".
Fuzzy and untranslated entries are skipped (the English text is shown).

    po_to_py.py <l10n dir> <out dir> [<NDS-Signer l10n dir>]
"""
import ast
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from ttf_to_ndsfont import TEXT_CHARS  # noqa: E402

GLYPHS = set(TEXT_CHARS) | {"\n", "\t"}


def parse_po(text):
    """[(msgid, msgid_plural, [msgstr...], fuzzy)] of a .po file."""
    entries, cur, field, fuzzy = [], None, None, False

    def flush():
        if cur is not None and cur.get("msgid"):
            forms = [cur[k] for k in sorted(k for k in cur if k.startswith("msgstr"))]
            entries.append((cur["msgid"], cur.get("msgid_plural"), forms, cur.get("fuzzy", False)))

    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            flush()
            cur, field, fuzzy = None, None, False
            continue
        if line.startswith("#,"):
            fuzzy = "fuzzy" in line
            continue
        if line.startswith("#"):
            continue
        if line.startswith('"'):
            cur[field] += ast.literal_eval(line)
            continue
        key, value = line.split(" ", 1)
        if key == "msgid":
            flush()
            cur = {"fuzzy": fuzzy}
        if key.startswith("msgstr["):
            key = "msgstr%s" % key[7:-1]
        cur[key] = ast.literal_eval(value)
        field = key
    flush()
    return entries


def main():
    l10n, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    extra = pathlib.Path(sys.argv[3]) if len(sys.argv) > 3 else None
    out.mkdir(parents=True, exist_ok=True)
    included = []
    for po in sorted(l10n.glob("*/LC_MESSAGES/messages.po")):
        locale = po.parent.parent.name
        messages, plurals = {}, {}
        entries = parse_po(po.read_text(encoding="utf-8"))
        if extra and (extra / ("%s.po" % locale)).exists():
            entries += parse_po((extra / ("%s.po" % locale)).read_text(encoding="utf-8"))
        for msgid, msgid_plural, forms, fuzzy in entries:
            if fuzzy or not any(forms):
                continue
            if msgid_plural:
                plurals[msgid] = forms
            else:
                messages[msgid] = forms[0]
        missing = sorted({c for s in list(messages.values()) + [f for fs in plurals.values() for f in fs]
                          for c in s if c not in GLYPHS})
        if missing:
            print("skip %-10s %d characters not in the fonts, e.g. %r" % (locale, len(missing),
                                                                          "".join(missing[:8])))
            continue
        (out / ("nds_l10n_%s.py" % locale)).write_text(
            "# GENERATED by tools/po_to_py.py from SeedSigner's translations (MIT)\n"
            "MESSAGES = %r\nPLURALS = %r\n" % (messages, plurals), encoding="utf-8")
        included.append(locale)
        print("ok   %-10s %d messages" % (locale, len(messages)))
    (out / "nds_l10n_index.py").write_text(
        "# GENERATED by tools/po_to_py.py\nLOCALES = %r\n" % included, encoding="utf-8")
    (out / "l10n_manifest.py").write_text(
        "# GENERATED by tools/po_to_py.py: translations frozen into the ROM\n" + "".join(
            'module("%s", base_path="$(PORT_DIR)/../build/frozen_py")\n' % name
            for name in ["nds_l10n_index.py"] + ["nds_l10n_%s.py" % loc for loc in included]),
        encoding="utf-8")


if __name__ == "__main__":
    main()
