#!/usr/bin/env python3
"""Rasterizes SeedSigner's fonts (third_party/seedsigner/src/seedsigner/
resources/fonts) into anti-aliased 4-bit glyph tables for NDS-Signer's
graphics renderer (arm9/src/gfx.c).

    ttf_to_ndsfont.py <seedsigner src dir> <out.c> <out.h>

Runs in the builder image (Pillow and FreeType pinned in the Dockerfile), so
the output is reproducible. Text fonts cover Latin-1 and Latin Extended-A
(the languages of SeedSigner's translations that use the Latin script);
icon fonts cover the code points of SeedSigner's icon constants
(gui/components.py).
"""
import pathlib
import re
import sys

from PIL import Image, ImageDraw, ImageFont

TEXT_CHARS = ([chr(c) for c in range(0x20, 0x7F)] + [chr(c) for c in range(0xA0, 0x180)]
              + list("–—‘’“”•…€→←↑↓"))

# (id, file, pixel size, charset); ids become GFX_FONT_<ID> in the header
FONTS = [
    ("BODY", "OpenSans-Regular.ttf", 13, "text"),
    ("BODY_BOLD", "OpenSans-SemiBold.ttf", 13, "text"),
    ("BUTTON", "OpenSans-SemiBold.ttf", 15, "text"),
    ("TITLE", "OpenSans-SemiBold.ttf", 17, "text"),
    ("LARGE", "OpenSans-SemiBold.ttf", 24, "text"),
    ("MONO", "Inconsolata-Regular.ttf", 14, "text"),
    ("MONO_SMALL", "Inconsolata-Regular.ttf", 12, "text"),
    ("MONO_BOLD", "Inconsolata-SemiBold.ttf", 16, "text"),
    ("ICON", "Font_Awesome_6_Free-Solid-900.otf", 16, "fa"),
    ("ICON_LARGE", "Font_Awesome_6_Free-Solid-900.otf", 26, "fa"),
    ("SSICON", "seedsigner-icons.otf", 16, "ss"),
    ("SSICON_LARGE", "seedsigner-icons.otf", 26, "ss"),
]


def icon_codepoints(components_py, class_name):
    """Code points of the string constants of an upstream icon class."""
    src = components_py.read_text()
    body = src.split("class %s" % class_name, 1)[1].split("\nclass ", 1)[0]
    points = set()
    for literal in re.findall(r'=\s*"((?:\\u[0-9a-fA-F]{4})+)"', body):
        for hexcode in re.findall(r"\\u([0-9a-fA-F]{4})", literal):
            points.add(chr(int(hexcode, 16)))
    return sorted(points)


def rasterize(font, ch):
    """Glyph bitmap as 0-15 alpha rows, and its metrics relative to the
    baseline: (w, h, left, top, advance) with top = rows above baseline."""
    ascent, _descent = font.getmetrics()
    left, top, right, bottom = font.getbbox(ch, anchor="ls")
    advance = int(round(font.getlength(ch)))
    w, h = max(0, right - left), max(0, bottom - top)
    if w == 0 or h == 0:
        return [], 0, 0, 0, 0, advance
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255, anchor="ls")
    px = img.load()
    rows = [[(px[x, y] + 8) // 17 for x in range(w)] for y in range(h)]
    return rows, w, h, left, -top, advance


def main():
    src, out_c, out_h = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
    fonts_dir = src / "seedsigner" / "resources" / "fonts"
    components = src / "seedsigner" / "gui" / "components.py"
    charsets = {
        "text": TEXT_CHARS,
        "fa": icon_codepoints(components, "FontAwesomeIconConstants"),
        "ss": icon_codepoints(components, "SeedSignerIconConstants"),
    }

    c = ["/* GENERATED by tools/ttf_to_ndsfont.py from SeedSigner's fonts - do not edit */",
         '#include "gfx_fonts.h"', ""]
    h = ["/* GENERATED by tools/ttf_to_ndsfont.py - do not edit */",
         "#ifndef NDS_SIGNER_GFX_FONTS_H", "#define NDS_SIGNER_GFX_FONTS_H", "",
         "#include <stdint.h>", "",
         "typedef struct {",
         "\tuint32_t codepoint;",
         "\tuint32_t offset;   /* into the font's pixel data: rows of 4-bit alpha, 2 px per byte */",
         "\tuint8_t w, h;",
         "\tint8_t left, top;  /* from the pen position on the baseline; top = rows above it */",
         "\tuint8_t advance;",
         "} GfxGlyph;", "",
         "typedef struct {",
         "\tconst GfxGlyph *glyphs;  /* sorted by code point */",
         "\tuint16_t count;",
         "\tuint8_t ascent, lineHeight;",
         "\tconst uint8_t *pixels;",
         "} GfxFont;", "",
         "enum {"]
    names = []
    for font_id, filename, size, charset in FONTS:
        font = ImageFont.truetype(str(fonts_dir / filename), size)
        ascent, descent = font.getmetrics()
        glyphs, data = [], bytearray()
        for ch in sorted(set(charsets[charset])):
            rows, w, hgt, left, top, advance = rasterize(font, ch)
            offset = len(data)
            for row in rows:
                row = row + [0] * (len(row) % 2)
                data += bytes((row[i] | (row[i + 1] << 4)) for i in range(0, len(row), 2))
            glyphs.append((ord(ch), offset, w, hgt, left, top, advance))
        name = font_id.lower()
        names.append(name)
        h.append("\tGFX_FONT_%s," % font_id)
        c.append("/* %s %dpx: %d glyphs, %d bytes */" % (filename, size, len(glyphs), len(data)))
        c.append("static const uint8_t s_%s_pixels[%d] = {" % (name, max(1, len(data))))
        for i in range(0, len(data), 24):
            c.append("\t" + ", ".join("0x%02x" % b for b in data[i:i + 24]) + ",")
        c.append("};")
        c.append("static const GfxGlyph s_%s_glyphs[%d] = {" % (name, len(glyphs)))
        for g in glyphs:
            c.append("\t{0x%x, %d, %d, %d, %d, %d, %d}," % g)
        c.append("};")
        c.append("")
    h += ["\tGFX_FONT_COUNT", "};", "", "extern const GfxFont g_gfxFonts[GFX_FONT_COUNT];", "",
          "#endif", ""]
    c.append("const GfxFont g_gfxFonts[GFX_FONT_COUNT] = {")
    for (font_id, filename, size, _cs), name in zip(FONTS, names):
        font = ImageFont.truetype(str(fonts_dir / filename), size)
        ascent, descent = font.getmetrics()
        c.append("\t{s_%s_glyphs, sizeof(s_%s_glyphs) / sizeof(GfxGlyph), %d, %d, s_%s_pixels},"
                 % (name, name, ascent, ascent + descent, name))
    c += ["};", ""]
    out_c.write_text("\n".join(c))
    out_h.write_text("\n".join(h))


if __name__ == "__main__":
    main()
