#!/usr/bin/env python3
"""Build-time source transform: upstream CPython code -> MicroPython.

Reads unmodified upstream Python (e.g. SeedSigner, from its pinned submodule)
and writes an equivalent, readable copy that MicroPython can run. Only
constructs MicroPython cannot support are rewritten:

  * @dataclass classes: MicroPython discards class annotations, so annotated
    fields are recorded in order in `__nds_fields__` and annotation-only lines
    are removed. The runtime shim (mpy/frozen/compat/dataclasses.py) builds
    __init__ from that list.
  * Annotated assignments in class bodies become plain assignments.
  * Subscripted generic bases (PEP 585), e.g. `class BackStack(list[X])`,
    become the plain type (`list`): identical at runtime, unsupported by
    MicroPython.
  * `cls.__new__(cls)` (SeedSigner's singletons) becomes
    `object.__new__(cls)`: MicroPython classes do not expose `__new__`. Only
    equivalent when no class defines its own `__new__`, which is checked.
  * f-strings become the equivalent "...".format(...) calls: MicroPython's
    f-string support is limited (e.g. no nested quotes, PEP 701).

Everything else is emitted as-is (via ast.unparse, so comments are dropped).

Usage:
    tools/upy_transform.py --src third_party/seedsigner/src --out build/frozen_py \\
        seedsigner/models/psbt_parser.py ...
"""
import argparse
import ast
import pathlib
import sys


def is_dataclass_decorator(node):
    target = node.func if isinstance(node, ast.Call) else node
    return (isinstance(target, ast.Name) and target.id == "dataclass") or (
        isinstance(target, ast.Attribute) and target.attr == "dataclass"
    )


class Transformer(ast.NodeTransformer):
    def visit_FunctionDef(self, node):
        if node.name == "__new__":
            raise SystemExit("upy_transform: custom __new__ found; the __new__ rewrite "
                             "would be wrong for it (line %d)" % node.lineno)
        self.generic_visit(node)
        return node

    def visit_Call(self, node):
        self.generic_visit(node)
        func = node.func
        if isinstance(func, ast.Attribute) and func.attr == "__new__" and not (
                isinstance(func.value, ast.Name) and func.value.id == "object"):
            node.func = ast.Attribute(value=ast.Name(id="object", ctx=ast.Load()),
                                      attr="__new__", ctx=ast.Load())
        return node

    def visit_JoinedStr(self, node):
        template, args = "", []
        for part in node.values:
            if isinstance(part, ast.Constant):
                template += part.value.replace("{", "{{").replace("}", "}}")
                continue
            part.value = self.visit(part.value)
            field = "{"
            if part.conversion != -1:
                field += "!" + chr(part.conversion)
            if part.format_spec is not None:
                spec = part.format_spec
                if not all(isinstance(v, ast.Constant) for v in spec.values):
                    raise SystemExit("upy_transform: dynamic f-string format spec (line %d)"
                                     % node.lineno)
                field += ":" + "".join(v.value for v in spec.values)
            template += field + "}"
            args.append(part.value)
        if not args:
            return ast.copy_location(ast.Constant(template.replace("{{", "{").replace("}}", "}")), node)
        call = ast.Call(func=ast.Attribute(value=ast.Constant(template), attr="format", ctx=ast.Load()),
                        args=args, keywords=[])
        return ast.copy_location(call, node)

    def visit_ClassDef(self, node):
        self.generic_visit(node)
        node.bases = [b.value if isinstance(b, ast.Subscript) else b for b in node.bases]
        is_dc = any(is_dataclass_decorator(d) for d in node.decorator_list)
        fields = []
        body = []
        for stmt in node.body:
            if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                name = stmt.target.id
                ann = ast.unparse(stmt.annotation)
                if is_dc and not ann.startswith("ClassVar"):
                    fields.append(name)
                if stmt.value is not None:
                    body.append(ast.copy_location(
                        ast.Assign(targets=[stmt.target], value=stmt.value), stmt))
                continue
            body.append(stmt)
        if is_dc:
            has_doc = body and isinstance(body[0], ast.Expr) and isinstance(
                getattr(body[0], "value", None), ast.Constant) and isinstance(body[0].value.value, str)
            body.insert(1 if has_doc else 0, ast.Assign(
                targets=[ast.Name(id="__nds_fields__", ctx=ast.Store())],
                value=ast.Tuple(elts=[ast.Constant(f) for f in fields], ctx=ast.Load()),
            ))
        if not body:
            body = [ast.Pass()]
        node.body = body
        return node


HEADER = (
    "# GENERATED by tools/upy_transform.py from upstream source: {src}\n"
    "# Do not edit; change the transform or the upstream pin instead.\n"
)


def transform(path: pathlib.Path, rel: str) -> str:
    tree = ast.parse(path.read_text(), filename=str(path))
    tree = Transformer().visit(tree)
    ast.fix_missing_locations(tree)
    return HEADER.format(src=rel) + ast.unparse(tree) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, type=pathlib.Path)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument("files", nargs="+")
    args = ap.parse_args()

    for rel in args.files:
        src = args.src / rel
        dst = args.out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(transform(src, rel))
        # make every directory a package, as upstream relies on implicit ones
        for parent in dst.parents:
            if parent == args.out or args.out not in parent.parents and parent != args.out:
                break
            init = parent / "__init__.py"
            if not init.exists():
                upstream_init = args.src / parent.relative_to(args.out) / "__init__.py"
                init.write_text(
                    transform(upstream_init, str(parent.relative_to(args.out) / "__init__.py"))
                    if upstream_init.exists() else "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
