#!/usr/bin/env python3
"""Build-time source transform: upstream CPython code -> MicroPython.

Reads unmodified upstream Python (e.g. SeedSigner, from its pinned submodule)
and writes an equivalent, readable copy that MicroPython can run. Only
constructs MicroPython cannot support are rewritten:

  * @dataclass classes: MicroPython discards class annotations, so annotated
    fields are recorded in order in `__nds_fields__` and annotation-only lines
    are removed. The runtime shim (mpy/frozen/compat/dataclasses.py) builds
    __init__ from that list.
  * Annotated assignments in class bodies become plain assignments.

Everything else is emitted as-is (via ast.unparse, so comments are dropped).

Usage:
    tools/upy_transform.py --src third_party/seedsigner/src --out build/frozen_py \\
        seedsigner/models/psbt_parser.py ...
"""
import argparse
import ast
import pathlib
import sys


def is_dataclass_decorator(node):
    target = node.func if isinstance(node, ast.Call) else node
    return (isinstance(target, ast.Name) and target.id == "dataclass") or (
        isinstance(target, ast.Attribute) and target.attr == "dataclass"
    )


class Transformer(ast.NodeTransformer):
    def visit_ClassDef(self, node):
        self.generic_visit(node)
        is_dc = any(is_dataclass_decorator(d) for d in node.decorator_list)
        fields = []
        body = []
        for stmt in node.body:
            if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                name = stmt.target.id
                ann = ast.unparse(stmt.annotation)
                if is_dc and not ann.startswith("ClassVar"):
                    fields.append(name)
                if stmt.value is not None:
                    body.append(ast.copy_location(
                        ast.Assign(targets=[stmt.target], value=stmt.value), stmt))
                continue
            body.append(stmt)
        if is_dc:
            has_doc = body and isinstance(body[0], ast.Expr) and isinstance(
                getattr(body[0], "value", None), ast.Constant) and isinstance(body[0].value.value, str)
            body.insert(1 if has_doc else 0, ast.Assign(
                targets=[ast.Name(id="__nds_fields__", ctx=ast.Store())],
                value=ast.Tuple(elts=[ast.Constant(f) for f in fields], ctx=ast.Load()),
            ))
        if not body:
            body = [ast.Pass()]
        node.body = body
        return node


HEADER = (
    "# GENERATED by tools/upy_transform.py from upstream source: {src}\n"
    "# Do not edit; change the transform or the upstream pin instead.\n"
)


def transform(path: pathlib.Path, rel: str) -> str:
    tree = ast.parse(path.read_text(), filename=str(path))
    tree = Transformer().visit(tree)
    ast.fix_missing_locations(tree)
    return HEADER.format(src=rel) + ast.unparse(tree) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, type=pathlib.Path)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    ap.add_argument("files", nargs="+")
    args = ap.parse_args()

    for rel in args.files:
        src = args.src / rel
        dst = args.out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(transform(src, rel))
        # make every directory a package, as upstream relies on implicit ones
        for parent in dst.parents:
            if parent == args.out or args.out not in parent.parents and parent != args.out:
                break
            init = parent / "__init__.py"
            if not init.exists():
                upstream_init = args.src / parent.relative_to(args.out) / "__init__.py"
                init.write_text(
                    transform(upstream_init, str(parent.relative_to(args.out) / "__init__.py"))
                    if upstream_init.exists() else "")
    return 0


if __name__ == "__main__":
    sys.exit(main())
